import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '../components/Header'
import HeroSection from '../components/HeroSection'
import Template1 from '../components/template/Template1'
import Template2 from '../components/template/Template2'
import Form from '../components/Form'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Rezumers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Header />
      <HeroSection /> */}
      <Template1/>
      <Template2/>
      <Form/>
    </>
  )
}
